"""init migration

Revision ID: 1ccc670e299
Revises: None
Create Date: 2015-08-07 15:46:43.694067

"""

# revision identifiers, used by Alembic.
revision = '1ccc670e299'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
