"""update Post Column 'timestamp'

Revision ID: 7c2ccb3e2d
Revises: 10adf78bec0
Create Date: 2015-08-11 22:32:27.178554

"""

# revision identifiers, used by Alembic.
revision = '7c2ccb3e2d'
down_revision = '10adf78bec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.drop_index('ix_posts_timestramp', table_name='posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_timestramp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    ### end Alembic commands ###
